name: jaxfem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - spyder
  - numpy
  - scipy
  - matplotlib
  - meshio
  - petsc4py
  - pip
  - pip:
    - jax
    - jaxlib
    - setuptools
    - wheel
    - gmsh
    - fenics-basix
    - pyfiglet
